### ISSUE TITLE
Feedback address

### ISSUE THREAD

**Issue by micdre** [arikadiusz/LightwaveRfGen2#2]
Hi,

Love your work!
I want to use your LightwaveRF module.
What is the FeedbackServer IP address? If my Crestron CP3 controller has 192.168.178.115 as the IP address should I use that IP then?

Kind regards, Michel Drenthen

**Comment by arikadiusz** [comment]
its the external IP of your network where CP3 is located. You will need to open ports to make it work. Lightwaverf API v2 is cloud based.

**Comment by arikadiusz** [comment]
This question was asked before. I am closing the case.

**Comment by micdre** [comment]
Ok thanks. Clear. 
And the Port to forward points to the IP of the Crestron controĺler?

⁣Verzonden door BlueMail ​

Op 26 aug. 2020 20:44, om 20:44, arikadiusz <notifications@github.com> schreef:

**Comment by arikadiusz** [comment]
Correct

**Comment by micdre** [comment]
Thank you!

⁣Verzonden door BlueMail ​

Op 26 aug. 2020 20:52, om 20:52, arikadiusz <notifications@github.com> schreef:
